name: cidc example

on:
  push: 
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      - run: echo "Construyendo la imagen de docker..."
      - run: docker build -f docker/Dockerfile -t app:build .
      - run: docker save -o app.tar app:build
      - run: ls -la
      - uses: actions/upload-artifact@v2
        with:
          name: docker_image
          path: app.tar
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: docker_image
      - run: ls -la
      - run: echo "Corriendo las pruebas"
      - run: docker load -i app.tar
      - run: docker run --rm --name test app:build npm test

  package:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: docker_image
      - run: ls -la
      - run: echo "docker push or docker save..."
      - run: docker load -i app.tar
      - run: docker tag app:build ricardcutzh/cicd-docker:$GITHUB_SHA
      - run: docker tag app:build ricardcutzh/cicd-docker:githublatest
      - name: Login to GitHub Package Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker push ricardcutzh/cicd-docker:$GITHUB_SHA
      - run: docker push ricardcutzh/cicd-docker:githublatest
      - run: echo "docker push finalizado"